/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.iisys.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Camunda service. Represents a row in the &quot;camunda_Camunda&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.iisys.model.impl.CamundaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.iisys.model.impl.CamundaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Camunda
 * @see de.iisys.model.impl.CamundaImpl
 * @see de.iisys.model.impl.CamundaModelImpl
 * @generated
 */
@ProviderType
public interface CamundaModel extends BaseModel<Camunda>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a camunda model instance should use the {@link Camunda} interface instead.
	 */

	/**
	 * Returns the primary key of this camunda.
	 *
	 * @return the primary key of this camunda
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this camunda.
	 *
	 * @param primaryKey the primary key of this camunda
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this camunda.
	 *
	 * @return the uuid of this camunda
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this camunda.
	 *
	 * @param uuid the uuid of this camunda
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the foo ID of this camunda.
	 *
	 * @return the foo ID of this camunda
	 */
	public long getFooId();

	/**
	 * Sets the foo ID of this camunda.
	 *
	 * @param fooId the foo ID of this camunda
	 */
	public void setFooId(long fooId);

	/**
	 * Returns the group ID of this camunda.
	 *
	 * @return the group ID of this camunda
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this camunda.
	 *
	 * @param groupId the group ID of this camunda
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this camunda.
	 *
	 * @return the company ID of this camunda
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this camunda.
	 *
	 * @param companyId the company ID of this camunda
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this camunda.
	 *
	 * @return the user ID of this camunda
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this camunda.
	 *
	 * @param userId the user ID of this camunda
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this camunda.
	 *
	 * @return the user uuid of this camunda
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this camunda.
	 *
	 * @param userUuid the user uuid of this camunda
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this camunda.
	 *
	 * @return the user name of this camunda
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this camunda.
	 *
	 * @param userName the user name of this camunda
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this camunda.
	 *
	 * @return the create date of this camunda
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this camunda.
	 *
	 * @param createDate the create date of this camunda
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this camunda.
	 *
	 * @return the modified date of this camunda
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this camunda.
	 *
	 * @param modifiedDate the modified date of this camunda
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the field1 of this camunda.
	 *
	 * @return the field1 of this camunda
	 */
	@AutoEscape
	public String getField1();

	/**
	 * Sets the field1 of this camunda.
	 *
	 * @param field1 the field1 of this camunda
	 */
	public void setField1(String field1);

	/**
	 * Returns the field2 of this camunda.
	 *
	 * @return the field2 of this camunda
	 */
	public boolean getField2();

	/**
	 * Returns <code>true</code> if this camunda is field2.
	 *
	 * @return <code>true</code> if this camunda is field2; <code>false</code> otherwise
	 */
	public boolean isField2();

	/**
	 * Sets whether this camunda is field2.
	 *
	 * @param field2 the field2 of this camunda
	 */
	public void setField2(boolean field2);

	/**
	 * Returns the field3 of this camunda.
	 *
	 * @return the field3 of this camunda
	 */
	public int getField3();

	/**
	 * Sets the field3 of this camunda.
	 *
	 * @param field3 the field3 of this camunda
	 */
	public void setField3(int field3);

	/**
	 * Returns the field4 of this camunda.
	 *
	 * @return the field4 of this camunda
	 */
	public Date getField4();

	/**
	 * Sets the field4 of this camunda.
	 *
	 * @param field4 the field4 of this camunda
	 */
	public void setField4(Date field4);

	/**
	 * Returns the field5 of this camunda.
	 *
	 * @return the field5 of this camunda
	 */
	@AutoEscape
	public String getField5();

	/**
	 * Sets the field5 of this camunda.
	 *
	 * @param field5 the field5 of this camunda
	 */
	public void setField5(String field5);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(de.iisys.model.Camunda camunda);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.iisys.model.Camunda> toCacheModel();

	@Override
	public de.iisys.model.Camunda toEscapedModel();

	@Override
	public de.iisys.model.Camunda toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}